
StylesPath = .vale

MinAlertLevel = suggestion

# run `vale sync` to install packages
Packages = proselint, alex, Readability

Vocab = Terms

[formats]
qmd = md

[*.{qmd}]
BasedOnStyles = Vale, proselint, alex, Readability
BlockIgnores = (@[\-_a-zA-Z0-9]+)|(`.+`)
proselint.Typography = No
alex.ProfanityUnlikely = No

# write-good is just complaining about passive tense and 'wordy' terms
# Readbility just complains about the following measurements:
# Flesch Reading Ease: 205 - W/P - 85 * S/W > 70  < 70/60/50 => (100-X)/4 !! probably uses P not S
# Flesch-Kincaid Grade Level: 0.4 * W/P + 12 * S/W - 16
# Gunning fog index: 0.4 * [ W/P + 100*D/W ]
# LIX (läsbarhetsindex): W/P + 100 * L/W  < 35/40/45  => X/3
# SMOG grade (Simple Measure of Gobbledygook): 3 + sqrt( 30 * D/P )
# ARI (automated readability index): 4.7 * C/W + 0.5 * W/P - 21.4
# Coleman–Liau index: 6 * C/W - 30 * P/W - 16
